version: '3.3'

services:
  mongocontainer:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db

  tg-bot:
    build: .
    depends_on:
      - mongocontainer
